---
name: HTML-Parser-Simple
version: 1.03
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: Parse nice HTML files without needing a compiler
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Carp: 0
  Tree::Simple: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  HTML::Parser::Simple:
    file: lib/HTML/Parser/Simple.pm
    version: 1.03
  HTML::Parser::Simple::Attributes:
    file: lib/HTML/Parser/Simple/Attributes.pm
    version: 1.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
